In [1]:
import numpy as np  # it is uses numerical operation , array , etc.  because in python array not exist.

1. Basic Array Creation

In [2]:
arr = np.array([1,2,3,4])  # array store similar datatypes 
arr

array([1, 2, 3, 4])

In [3]:
list = [1,2,3.5,4,"hello"]  #  list store similiar and non similar both dataptypes
list

[1, 2, 3.5, 4, 'hello']

In [4]:
np.array(list)  # if we pass a list with non - similar datatypes into an array then array will convert all the data into bigger datapye which is present in list.
                # here all data converted into string. (because in list string present).

array(['1', '2', '3.5', '4', 'hello'], dtype='<U32')

In [5]:
l = [[1,2,3], [4,5,6], [7,8,9]]  # this is one dimensional in list.list not provide multidimensionality. called vector.
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(l)  # this is provide multidimesional array. this is 2D dimensional array matrix.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2. Array generation function

In [7]:
arr1 = np.arange(1,11)  # this generate 1 to 10 countinuously. last no not included.
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr2 = np.arange(1,11,2)  # this generate between 1 to 11 with the gap of 2. last no not included.
arr2

array([1, 3, 5, 7, 9])

In [9]:
arr3 = np.zeros(6)  # generate zeros according passing values. here 6
arr3

array([0., 0., 0., 0., 0., 0.])

In [10]:
arr4 = np.zeros((5,6))   # generate zeros matrix according passing values. here 5 x 6
arr4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
arr5 = np.ones(5)  # this generate ones. 5 times.
arr5

array([1., 1., 1., 1., 1.])

In [12]:
arr6 = np.ones((5,6))  # this generate ones matrix . 5x6
arr6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
arr7 = np.linspace(1,11,6)  # this gives a linear space (equal space between all nubmers) between given range. last parameter tells how many numbers you want.
arr7

array([ 1.,  3.,  5.,  7.,  9., 11.])

3. Random Generation function

In [14]:
np.random.rand(10)   # randomaly generates numbers according input. This is also called Normlization (all values between (0 - 1)).

array([0.45823765, 0.82906312, 0.7552818 , 0.21441969, 0.01786211,
       0.88096161, 0.37505998, 0.02027898, 0.84698886, 0.88292335])

In [15]:
np.random.randn(10)  # this is also generates random numbers according input. This is also called Standirization (all values between (-3 - 3)).

array([-0.26189311, -0.75006176,  0.82354494,  0.43171669, -0.78915961,
        1.57021683, -0.88605508, -0.78193451, -1.05312972, -1.56864136])

In [16]:
np.random.randint(5)  # this generate only one integer number bettween 0 to 5.

2

In [17]:
np.random.randint(2,10,5)  # this generate  5 numbers between 2 to 10 . last parameter tells how many no. you want to generate.

array([5, 5, 7, 5, 3], dtype=int32)

4. Array Attributes. --->>
   in attributes no bracket allowed. uses without brackets.

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.shape  # give the shape of array matrix. (3x3)

(3, 3)

In [20]:
arr.size  # give the size of array matrix.(how many elements in matrix)

9

In [21]:
arr.dtype  # tells about datatpye of array matrix.

dtype('int64')

6. Array Methods

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr.min()  # give minimum value 

np.int64(1)

In [24]:
arr.max() # give maximum value

np.int64(9)

In [25]:
arr.sum()  # sum all of values in matrix

np.int64(45)

In [26]:
np.sum(arr, axis = 0)  # sum of values column wise (axis = 0)

array([12, 15, 18])

In [27]:
np.sum(arr,axis = 1)  # sum of values row wise (axis = 1)

array([ 6, 15, 24])

In [28]:
arr.mean()  # give mean of matrix of all numbers.

np.float64(5.0)

In [29]:
arr.std()  # give standard deviation of matrix of all numbers.

np.float64(2.581988897471611)

In [30]:
arr.argmax()  # gives the index of maximum value of a matrix.

np.int64(8)

In [31]:
arr.argmin()  # give the index of minimum value of a matrix.

np.int64(0)

7. Reshaping and Resizing

In [32]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
arr = arr.reshape(6,5)  #  during reshaping the array matrix , note that the numbers of element in array = numbers in reshaping array.
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])