In [1]:
import numpy as np

ARRAY OPERATIONS

Arithmetic operations   ---->  for arithmetic operations both array size must be same.

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [3]:
# for arithmetic operations both array size must be same
a1 + a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [9]:
a1 // a2  # floor division

array([0, 0, 0, 0, 0])

In [11]:
a1 ** a2  # power

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [13]:
list = [10,20,30,40]
arr= np.array(list)

In [14]:
for i in list:
    print(i+10)

20
30
40
50


In [16]:
arr + 10  #  broadcasting using array , which is not possible in list . (above method follow in list)

array([20, 30, 40, 50])

In [17]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
arr2 + 20

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

Deep copy and Shallow copy

In [19]:
# shallow copy --> in shallow copy when we slice a vectoe or matrix, changes  made will be reflected  nested in original vector or matrix.
# deep copy ---> create new copy of array. not affected original array.
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [22]:
a   # not changes in original array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
a[4:6] *10

array([50, 60])

In [24]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
# b = a.copy()  # here if we changed in b , if .copy used then original array not changed
b = a   # here if we changed in b then original array also changed
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [36]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [37]:
A

array([[1, 2],
       [3, 4]])

In [38]:
B

array([[5, 6],
       [7, 8]])

In [40]:
A @ B  # two matrix multiplication --->> we use @ sign

array([[19, 22],
       [43, 50]])

In [42]:
np.dot(A,B)  # two matrix multiplication (dot product)

array([[19, 22],
       [43, 50]])

In [43]:
A

array([[1, 2],
       [3, 4]])

In [46]:
A.T   # Transpose matrix (use T)

array([[1, 3],
       [2, 4]])

ADVANCE ARRAY MANIPULATION

In [49]:
# we can not stack two matrix. because they already stacked. so,
# we can stack two arrays(vectors)

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])



In [50]:
a

array([1, 2, 3, 4])

In [51]:
b

array([5, 6, 7, 8])

In [56]:
np.vstack((a,b))  # vertically stack add row wise

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
np.hstack((a,b))  # horizontally stack join two arrays

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
np.column_stack((a,b))  # column stack make column of arrays

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [59]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
np.hsplit(c,2)  ## split array in to 2 equl 2D array  horizontaly

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [63]:
np.hsplit(c,4)  # split array in to 4 equl 2D array horizontaly

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [67]:
np.vsplit(c,2)  ## split array in to 2 equl 2D array vertically

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [72]:
a = np.vsplit(c,4)   ### split array in to 4 equl 2D array vertically
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [73]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
