In [1]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
arr[0]  # indexing starts from zero
arr[1]
arr[2]
arr[3]
arr[4]
arr[5]
arr[6]
arr[7]
arr[8]
arr[9]

np.int64(20)

In [33]:
# slicing
# arr[start : end(excluded)]
arr_slice = arr[2:5]  #  index 2 to 4
arr_slice


array([13, 14, 15])

In [34]:
# arr[ : end]  --> start(0) to 6
arr_slice = arr[:6]
arr_slice

array([11, 12, 13, 14, 15, 16])

In [35]:
# arr[start : ]   -->> start(3) to end
arr_slice = arr[3 : ]
arr_slice

array([14, 15, 16, 17, 18, 19, 20])

In [36]:
# arr[ : ]   -->>> start to end all element
arr_slice = arr[ : ]  # complete row
arr_slice

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
# arr[start : end : step(gap)]   ---->> start(2) to end(6) with gap 2 --> 13,15,17
arr_slice = arr[2 : 8 : 2]
arr_slice

array([13, 15, 17])

In [38]:
arr_slice = arr[1 : : 2]
arr_slice

array([12, 14, 16, 18, 20])

NUMPY INDEXING AND SLICING OF MATRIX

In [40]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [42]:
arr[0]   # print 0th row
arr[1]   # print 1th row etc.

array([ 6,  7,  8,  9, 10])

In [44]:
 #  single element finding
#  arr[row_index, column_index]
arr[0,0]  

np.int64(1)

In [49]:
#  fnding a part of matrix
#  arr[row_start : row_end(excluded) , column_start : column_end(excluded)]
part_slice = arr[0:2 , 1:4]
part_slice

array([[2, 3, 4],
       [7, 8, 9]])

In [52]:
part_slice1 = arr[3:6 , 3:5]
part_slice1

array([[19, 20],
       [24, 25],
       [29, 30]])

In [54]:
part_slice2 = arr[3:,3:]   # row goes 3 to last and column goes 3 to last
part_slice2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [58]:
# print columns
#  arr[:,column_index]  --->> select all rows & given column
arr[:,4]  # print column 3

array([ 5, 10, 15, 20, 25, 30])

BOOLEAN INDEXING

In [64]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
bool_index = arr % 2 == 0
bool_index

array([ True,  True,  True,  True,  True])

In [71]:
arr = arr[bool_index]  # in array where value are true they will kept and remove others false values
arr

array([ 2,  4,  6,  8, 10])